"""create problems table

Revision ID: 295e0b079d24
Revises: e04e5d6bfef3
Create Date: 2026-05-20 09:41:28.622835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295e0b079d24'
down_revision: Union[str, Sequence[str], None] = 'e04e5d6bfef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('input_format', sa.Text(), nullable=False),
    sa.Column('output_format', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=False),
    sa.Column('sample_input', sa.Text(), nullable=False),
    sa.Column('sample_output', sa.Text(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('memory_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems')
    # ### end Alembic commands ###
